// Copyright 2025 The Flutter Authors.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import 'package:freezed_annotation/freezed_annotation.dart';

import 'part.dart';

part 'message.freezed.dart';
part 'message.g.dart';

/// Identifies the sender of a [Message].
enum Role {
  /// The message is from the user (i.e., the A2A client).
  user,

  /// The message is from the agent (i.e., the A2A server).
  agent,
}

/// Represents a single communication turn between a client and an agent.
///
/// Messages are used for instructions, prompts, replies, and status updates.
/// A message is composed of one or more [Part]s.
@freezed
abstract class Message with _$Message {
  /// Creates a [Message].
  const factory Message({
    /// Identifies the sender of the message. `user` for the client, `agent` for
    /// the service.
    required Role role,

    /// An array of content parts that form the message body. A message can be
    /// composed of multiple parts of different types (e.g., text and files).
    required List<Part> parts,

    /// Optional metadata for extensions. The key is an extension-specific
    /// identifier.
    Map<String, Object?>? metadata,

    /// The URIs of extensions that are relevant to this message.
    List<String>? extensions,

    /// A list of other task IDs that this message references for additional
    /// context.
    List<String>? referenceTaskIds,

    /// A unique identifier for the message, typically a UUID, generated by the
    /// sender.
    required String messageId,

    /// The ID of the task this message is part of. Can be omitted for the first
    /// message of a new task.
    String? taskId,

    /// The context ID for this message, used to group related interactions.
    String? contextId,

    /// The type of this object, used as a discriminator. Always 'message' for a
    /// Message.
    @Default('message') String kind,
  }) = _Message;

  /// Creates a [Message] from a JSON object.
  factory Message.fromJson(Map<String, Object?> json) =>
      _$MessageFromJson(json);
}
