name: genui_client
description: "An app that generates user interfaces on the fly using AI."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  collection: ^1.19.1
  file: ^7.0.1
  firebase_ai: ^2.2.1
  firebase_app_check: ^0.3.0+1
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0
  flutter:
    sdk: flutter
  flutter_genui:
    path: ../../pkgs/flutter_genui
  json_rpc_2: ^4.0.0
  platform: ^3.1.6
  stream_channel: ^2.1.4

dev_dependencies:
  dart_flutter_team_lints: ^3.5.2
  fake_async: ^1.3.3
  flutter_test:
    sdk: flutter
  network_image_mock: ^2.1.1
  mockito: ^5.4.4

flutter:
  uses-material-design: true
