import 'package:freezed_annotation/freezed_annotation.dart';

import 'part.dart';

part 'message.freezed.dart';
part 'message.g.dart';

/// Identifies the sender of the message. `user` for the client, `agent` for the
/// service.
enum Role { user, agent }

/// Represents a single message in the conversation between a user and an agent.
@freezed
abstract class Message with _$Message {
  const factory Message({
    /// Identifies the sender of the message.
    required Role role,

    /// An array of content parts that form the message body.
    required List<Part> parts,

    /// Optional metadata for extensions.
    Map<String, dynamic>? metadata,

    /// The URIs of extensions that are relevant to this message.
    List<String>? extensions,

    /// A list of other task IDs that this message references for additional
    /// context.
    List<String>? referenceTaskIds,

    /// A unique identifier for the message, typically a UUID, generated by the
    /// sender.
    required String messageId,

    /// The ID of the task this message is part of.
    String? taskId,

    /// The context ID for this message, used to group related interactions.
    String? contextId,

    /// The type of this object, used as a discriminator. Always 'message' for a
    /// Message.
    @Default('message') String kind,
  }) = _Message;

  factory Message.fromJson(Map<String, dynamic> json) =>
      _$MessageFromJson(json);
}
