import 'package:freezed_annotation/freezed_annotation.dart';

import 'part.dart';

part 'message.freezed.dart';
part 'message.g.dart';

/// Identifies the sender of a message.
enum Role {
  /// The message is from the user (i.e., the client).
  user,

  /// The message is from the agent (i.e., the server).
  agent,
}

/// Represents a single message in the conversation between a user and an agent.
///
/// A message is composed of one or more [Part]s, which can be text, images, or
/// other types of content.
@freezed
abstract class Message with _$Message {
  /// Creates a [Message].
  const factory Message({
    /// Identifies the sender of the message.
    required Role role,

    /// An array of content parts that form the message body.
    required List<Part> parts,

    /// Optional metadata for extensions.
    Map<String, dynamic>? metadata,

    /// The URIs of extensions that are relevant to this message.
    List<String>? extensions,

    /// A list of other task IDs that this message references for additional
    /// context.
    List<String>? referenceTaskIds,

    /// A unique identifier for the message, typically a UUID, generated by the
    /// sender.
    required String messageId,

    /// The ID of the task this message is part of.
    String? taskId,

    /// The context ID for this message, used to group related interactions.
    String? contextId,

    /// The type of this object, used as a discriminator. Always 'message' for a
    /// Message.
    @Default('message') String kind,
  }) = _Message;

  /// Creates a [Message] from a JSON object.
  factory Message.fromJson(Map<String, dynamic> json) =>
      _$MessageFromJson(json);
}
