import 'package:freezed_annotation/freezed_annotation.dart';

import 'message.dart';
import 'part.dart';

part 'task.freezed.dart';

part 'task.g.dart';

/// Represents a single, stateful operation or conversation between a client and
/// an agent.
@freezed
abstract class Task with _$Task {
  /// Creates a [Task].
  const factory Task({
    /// A unique identifier (e.g., a UUID) for the task, generated by the server
    /// for a new task.
    required String id,

    /// A server-generated unique identifier (e.g., a UUID) for maintaining context
    /// across multiple related tasks or interactions.
    required String contextId,

    /// The current status of the task, including its state and a descriptive
    /// message.
    required TaskStatus status,

    /// An array of messages exchanged during the task, representing the
    /// conversation history.
    List<Message>? history,

    /// A collection of artifacts generated by the agent during the execution of
    /// the task.
    List<Artifact>? artifacts,

    /// Optional metadata for extensions. The key is an extension-specific
    /// identifier.
    Map<String, dynamic>? metadata,

    /// The type of this object, used as a discriminator. Always 'task' for a Task.
    @Default('task') String kind,
  }) = _Task;

  /// Creates a [Task] from a JSON object.
  factory Task.fromJson(Map<String, dynamic> json) => _$TaskFromJson(json);
}

/// Represents the status of a task at a specific point in time.
@freezed
abstract class TaskStatus with _$TaskStatus {
  /// Creates a [TaskStatus].
  const factory TaskStatus({
    /// The current state of the task's lifecycle.
    required TaskState state,

    /// An optional, human-readable message providing more details about the
    /// current status.
    Message? message,

    /// An ISO 8601 datetime string indicating when this status was recorded.
    String? timestamp,
  }) = _TaskStatus;

  /// Creates a [TaskStatus] from a JSON object.
  factory TaskStatus.fromJson(Map<String, dynamic> json) =>
      _$TaskStatusFromJson(json);
}

/// Defines the lifecycle states of a [Task].
enum TaskState {
  /// The task has been submitted and is awaiting execution.
  submitted,

  /// The agent is actively working on the task.
  working,

  /// The task is paused and waiting for input from the user.
  inputRequired,

  /// The task has been successfully completed.
  completed,

  /// The task has been canceled by the user.
  canceled,

  /// The task failed due to an error during execution.
  failed,

  /// The task was rejected by the agent and was not started.
  rejected,

  /// The task requires authentication to proceed.
  authRequired,

  /// The task is in an unknown or indeterminate state.
  unknown,
}

/// Represents a file, data structure, or other resource generated by an agent
/// during a task.
@freezed
abstract class Artifact with _$Artifact {
  /// Creates an [Artifact].
  const factory Artifact({
    /// A unique identifier (e.g., a UUID) for the artifact within the scope of the
    /// task.
    required String artifactId,

    /// An optional, human-readable name for the artifact.
    String? name,

    /// An optional, human-readable description of the artifact.
    String? description,

    /// An array of content parts that make up the artifact.
    required List<Part> parts,

    /// Optional metadata for extensions. The key is an extension-specific
    /// identifier.
    Map<String, dynamic>? metadata,

    /// The URIs of extensions that are relevant to this artifact.
    List<String>? extensions,
  }) = _Artifact;

  /// Creates an [Artifact] from a JSON object.
  factory Artifact.fromJson(Map<String, dynamic> json) =>
      _$ArtifactFromJson(json);
}
