// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, deprecated_member_use, deprecated_member_use_from_same_package, use_function_type_syntax_for_parameters, unnecessary_const, avoid_init_to_null, invalid_override_different_default_values_named, prefer_expression_function_bodies, annotate_overrides, invalid_annotation_target, unnecessary_question_mark

part of 'task.dart';

// **************************************************************************
// FreezedGenerator
// **************************************************************************

// dart format off
T _$identity<T>(T value) => value;

/// @nodoc
mixin _$Task {
  /// A unique identifier (e.g. UUID) for the task, generated by the server for
  /// a new task.
  String get id;

  /// A server-generated unique identifier (e.g. UUID) for maintaining context
  /// across multiple related tasks or interactions.
  String get contextId;

  /// The current status of the task, including its state and a descriptive
  /// message.
  TaskStatus get status;

  /// An array of messages exchanged during the task, representing the
  /// conversation history.
  List<Message>? get history;

  /// A collection of artifacts generated by the agent during the execution of
  /// the task.
  List<Artifact>? get artifacts;

  /// Optional metadata for extensions. The key is an extension-specific
  /// identifier.
  Map<String, dynamic>? get metadata;

  /// The type of this object, used as a discriminator. Always 'task' for a Task.
  String get kind;

  /// Create a copy of Task
  /// with the given fields replaced by the non-null parameter values.
  @JsonKey(includeFromJson: false, includeToJson: false)
  @pragma('vm:prefer-inline')
  $TaskCopyWith<Task> get copyWith =>
      _$TaskCopyWithImpl<Task>(this as Task, _$identity);

  /// Serializes this Task to a JSON map.
  Map<String, dynamic> toJson();

  @override
  bool operator ==(Object other) {
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is Task &&
            (identical(other.id, id) || other.id == id) &&
            (identical(other.contextId, contextId) ||
                other.contextId == contextId) &&
            (identical(other.status, status) || other.status == status) &&
            const DeepCollectionEquality().equals(other.history, history) &&
            const DeepCollectionEquality().equals(other.artifacts, artifacts) &&
            const DeepCollectionEquality().equals(other.metadata, metadata) &&
            (identical(other.kind, kind) || other.kind == kind));
  }

  @JsonKey(includeFromJson: false, includeToJson: false)
  @override
  int get hashCode => Object.hash(
      runtimeType,
      id,
      contextId,
      status,
      const DeepCollectionEquality().hash(history),
      const DeepCollectionEquality().hash(artifacts),
      const DeepCollectionEquality().hash(metadata),
      kind);

  @override
  String toString() {
    return 'Task(id: $id, contextId: $contextId, status: $status, history: $history, artifacts: $artifacts, metadata: $metadata, kind: $kind)';
  }
}

/// @nodoc
abstract mixin class $TaskCopyWith<$Res> {
  factory $TaskCopyWith(Task value, $Res Function(Task) _then) =
      _$TaskCopyWithImpl;
  @useResult
  $Res call(
      {String id,
      String contextId,
      TaskStatus status,
      List<Message>? history,
      List<Artifact>? artifacts,
      Map<String, dynamic>? metadata,
      String kind});

  $TaskStatusCopyWith<$Res> get status;
}

/// @nodoc
class _$TaskCopyWithImpl<$Res> implements $TaskCopyWith<$Res> {
  _$TaskCopyWithImpl(this._self, this._then);

  final Task _self;
  final $Res Function(Task) _then;

  /// Create a copy of Task
  /// with the given fields replaced by the non-null parameter values.
  @pragma('vm:prefer-inline')
  @override
  $Res call({
    Object? id = null,
    Object? contextId = null,
    Object? status = null,
    Object? history = freezed,
    Object? artifacts = freezed,
    Object? metadata = freezed,
    Object? kind = null,
  }) {
    return _then(_self.copyWith(
      id: null == id
          ? _self.id
          : id // ignore: cast_nullable_to_non_nullable
              as String,
      contextId: null == contextId
          ? _self.contextId
          : contextId // ignore: cast_nullable_to_non_nullable
              as String,
      status: null == status
          ? _self.status
          : status // ignore: cast_nullable_to_non_nullable
              as TaskStatus,
      history: freezed == history
          ? _self.history
          : history // ignore: cast_nullable_to_non_nullable
              as List<Message>?,
      artifacts: freezed == artifacts
          ? _self.artifacts
          : artifacts // ignore: cast_nullable_to_non_nullable
              as List<Artifact>?,
      metadata: freezed == metadata
          ? _self.metadata
          : metadata // ignore: cast_nullable_to_non_nullable
              as Map<String, dynamic>?,
      kind: null == kind
          ? _self.kind
          : kind // ignore: cast_nullable_to_non_nullable
              as String,
    ));
  }

  /// Create a copy of Task
  /// with the given fields replaced by the non-null parameter values.
  @override
  @pragma('vm:prefer-inline')
  $TaskStatusCopyWith<$Res> get status {
    return $TaskStatusCopyWith<$Res>(_self.status, (value) {
      return _then(_self.copyWith(status: value));
    });
  }
}

/// Adds pattern-matching-related methods to [Task].
extension TaskPatterns on Task {
  /// A variant of `map` that fallback to returning `orElse`.
  ///
  /// It is equivalent to doing:
  /// ```dart
  /// switch (sealedClass) {
  ///   case final Subclass value:
  ///     return ...;
  ///   case _:
  ///     return orElse();
  /// }
  /// ```

  @optionalTypeArgs
  TResult maybeMap<TResult extends Object?>(
    TResult Function(_Task value)? $default, {
    required TResult orElse(),
  }) {
    final _that = this;
    switch (_that) {
      case _Task() when $default != null:
        return $default(_that);
      case _:
        return orElse();
    }
  }

  /// A `switch`-like method, using callbacks.
  ///
  /// Callbacks receives the raw object, upcasted.
  /// It is equivalent to doing:
  /// ```dart
  /// switch (sealedClass) {
  ///   case final Subclass value:
  ///     return ...;
  ///   case final Subclass2 value:
  ///     return ...;
  /// }
  /// ```

  @optionalTypeArgs
  TResult map<TResult extends Object?>(
    TResult Function(_Task value) $default,
  ) {
    final _that = this;
    switch (_that) {
      case _Task():
        return $default(_that);
      case _:
        throw StateError('Unexpected subclass');
    }
  }

  /// A variant of `map` that fallback to returning `null`.
  ///
  /// It is equivalent to doing:
  /// ```dart
  /// switch (sealedClass) {
  ///   case final Subclass value:
  ///     return ...;
  ///   case _:
  ///     return null;
  /// }
  /// ```

  @optionalTypeArgs
  TResult? mapOrNull<TResult extends Object?>(
    TResult? Function(_Task value)? $default,
  ) {
    final _that = this;
    switch (_that) {
      case _Task() when $default != null:
        return $default(_that);
      case _:
        return null;
    }
  }

  /// A variant of `when` that fallback to an `orElse` callback.
  ///
  /// It is equivalent to doing:
  /// ```dart
  /// switch (sealedClass) {
  ///   case Subclass(:final field):
  ///     return ...;
  ///   case _:
  ///     return orElse();
  /// }
  /// ```

  @optionalTypeArgs
  TResult maybeWhen<TResult extends Object?>(
    TResult Function(
            String id,
            String contextId,
            TaskStatus status,
            List<Message>? history,
            List<Artifact>? artifacts,
            Map<String, dynamic>? metadata,
            String kind)?
        $default, {
    required TResult orElse(),
  }) {
    final _that = this;
    switch (_that) {
      case _Task() when $default != null:
        return $default(_that.id, _that.contextId, _that.status, _that.history,
            _that.artifacts, _that.metadata, _that.kind);
      case _:
        return orElse();
    }
  }

  /// A `switch`-like method, using callbacks.
  ///
  /// As opposed to `map`, this offers destructuring.
  /// It is equivalent to doing:
  /// ```dart
  /// switch (sealedClass) {
  ///   case Subclass(:final field):
  ///     return ...;
  ///   case Subclass2(:final field2):
  ///     return ...;
  /// }
  /// ```

  @optionalTypeArgs
  TResult when<TResult extends Object?>(
    TResult Function(
            String id,
            String contextId,
            TaskStatus status,
            List<Message>? history,
            List<Artifact>? artifacts,
            Map<String, dynamic>? metadata,
            String kind)
        $default,
  ) {
    final _that = this;
    switch (_that) {
      case _Task():
        return $default(_that.id, _that.contextId, _that.status, _that.history,
            _that.artifacts, _that.metadata, _that.kind);
      case _:
        throw StateError('Unexpected subclass');
    }
  }

  /// A variant of `when` that fallback to returning `null`
  ///
  /// It is equivalent to doing:
  /// ```dart
  /// switch (sealedClass) {
  ///   case Subclass(:final field):
  ///     return ...;
  ///   case _:
  ///     return null;
  /// }
  /// ```

  @optionalTypeArgs
  TResult? whenOrNull<TResult extends Object?>(
    TResult? Function(
            String id,
            String contextId,
            TaskStatus status,
            List<Message>? history,
            List<Artifact>? artifacts,
            Map<String, dynamic>? metadata,
            String kind)?
        $default,
  ) {
    final _that = this;
    switch (_that) {
      case _Task() when $default != null:
        return $default(_that.id, _that.contextId, _that.status, _that.history,
            _that.artifacts, _that.metadata, _that.kind);
      case _:
        return null;
    }
  }
}

/// @nodoc
@JsonSerializable()
class _Task implements Task {
  const _Task(
      {required this.id,
      required this.contextId,
      required this.status,
      final List<Message>? history,
      final List<Artifact>? artifacts,
      final Map<String, dynamic>? metadata,
      this.kind = 'task'})
      : _history = history,
        _artifacts = artifacts,
        _metadata = metadata;
  factory _Task.fromJson(Map<String, dynamic> json) => _$TaskFromJson(json);

  /// A unique identifier (e.g. UUID) for the task, generated by the server for
  /// a new task.
  @override
  final String id;

  /// A server-generated unique identifier (e.g. UUID) for maintaining context
  /// across multiple related tasks or interactions.
  @override
  final String contextId;

  /// The current status of the task, including its state and a descriptive
  /// message.
  @override
  final TaskStatus status;

  /// An array of messages exchanged during the task, representing the
  /// conversation history.
  final List<Message>? _history;

  /// An array of messages exchanged during the task, representing the
  /// conversation history.
  @override
  List<Message>? get history {
    final value = _history;
    if (value == null) return null;
    if (_history is EqualUnmodifiableListView) return _history;
    // ignore: implicit_dynamic_type
    return EqualUnmodifiableListView(value);
  }

  /// A collection of artifacts generated by the agent during the execution of
  /// the task.
  final List<Artifact>? _artifacts;

  /// A collection of artifacts generated by the agent during the execution of
  /// the task.
  @override
  List<Artifact>? get artifacts {
    final value = _artifacts;
    if (value == null) return null;
    if (_artifacts is EqualUnmodifiableListView) return _artifacts;
    // ignore: implicit_dynamic_type
    return EqualUnmodifiableListView(value);
  }

  /// Optional metadata for extensions. The key is an extension-specific
  /// identifier.
  final Map<String, dynamic>? _metadata;

  /// Optional metadata for extensions. The key is an extension-specific
  /// identifier.
  @override
  Map<String, dynamic>? get metadata {
    final value = _metadata;
    if (value == null) return null;
    if (_metadata is EqualUnmodifiableMapView) return _metadata;
    // ignore: implicit_dynamic_type
    return EqualUnmodifiableMapView(value);
  }

  /// The type of this object, used as a discriminator. Always 'task' for a Task.
  @override
  @JsonKey()
  final String kind;

  /// Create a copy of Task
  /// with the given fields replaced by the non-null parameter values.
  @override
  @JsonKey(includeFromJson: false, includeToJson: false)
  @pragma('vm:prefer-inline')
  _$TaskCopyWith<_Task> get copyWith =>
      __$TaskCopyWithImpl<_Task>(this, _$identity);

  @override
  Map<String, dynamic> toJson() {
    return _$TaskToJson(
      this,
    );
  }

  @override
  bool operator ==(Object other) {
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is _Task &&
            (identical(other.id, id) || other.id == id) &&
            (identical(other.contextId, contextId) ||
                other.contextId == contextId) &&
            (identical(other.status, status) || other.status == status) &&
            const DeepCollectionEquality().equals(other._history, _history) &&
            const DeepCollectionEquality()
                .equals(other._artifacts, _artifacts) &&
            const DeepCollectionEquality().equals(other._metadata, _metadata) &&
            (identical(other.kind, kind) || other.kind == kind));
  }

  @JsonKey(includeFromJson: false, includeToJson: false)
  @override
  int get hashCode => Object.hash(
      runtimeType,
      id,
      contextId,
      status,
      const DeepCollectionEquality().hash(_history),
      const DeepCollectionEquality().hash(_artifacts),
      const DeepCollectionEquality().hash(_metadata),
      kind);

  @override
  String toString() {
    return 'Task(id: $id, contextId: $contextId, status: $status, history: $history, artifacts: $artifacts, metadata: $metadata, kind: $kind)';
  }
}

/// @nodoc
abstract mixin class _$TaskCopyWith<$Res> implements $TaskCopyWith<$Res> {
  factory _$TaskCopyWith(_Task value, $Res Function(_Task) _then) =
      __$TaskCopyWithImpl;
  @override
  @useResult
  $Res call(
      {String id,
      String contextId,
      TaskStatus status,
      List<Message>? history,
      List<Artifact>? artifacts,
      Map<String, dynamic>? metadata,
      String kind});

  @override
  $TaskStatusCopyWith<$Res> get status;
}

/// @nodoc
class __$TaskCopyWithImpl<$Res> implements _$TaskCopyWith<$Res> {
  __$TaskCopyWithImpl(this._self, this._then);

  final _Task _self;
  final $Res Function(_Task) _then;

  /// Create a copy of Task
  /// with the given fields replaced by the non-null parameter values.
  @override
  @pragma('vm:prefer-inline')
  $Res call({
    Object? id = null,
    Object? contextId = null,
    Object? status = null,
    Object? history = freezed,
    Object? artifacts = freezed,
    Object? metadata = freezed,
    Object? kind = null,
  }) {
    return _then(_Task(
      id: null == id
          ? _self.id
          : id // ignore: cast_nullable_to_non_nullable
              as String,
      contextId: null == contextId
          ? _self.contextId
          : contextId // ignore: cast_nullable_to_non_nullable
              as String,
      status: null == status
          ? _self.status
          : status // ignore: cast_nullable_to_non_nullable
              as TaskStatus,
      history: freezed == history
          ? _self._history
          : history // ignore: cast_nullable_to_non_nullable
              as List<Message>?,
      artifacts: freezed == artifacts
          ? _self._artifacts
          : artifacts // ignore: cast_nullable_to_non_nullable
              as List<Artifact>?,
      metadata: freezed == metadata
          ? _self._metadata
          : metadata // ignore: cast_nullable_to_non_nullable
              as Map<String, dynamic>?,
      kind: null == kind
          ? _self.kind
          : kind // ignore: cast_nullable_to_non_nullable
              as String,
    ));
  }

  /// Create a copy of Task
  /// with the given fields replaced by the non-null parameter values.
  @override
  @pragma('vm:prefer-inline')
  $TaskStatusCopyWith<$Res> get status {
    return $TaskStatusCopyWith<$Res>(_self.status, (value) {
      return _then(_self.copyWith(status: value));
    });
  }
}

/// @nodoc
mixin _$TaskStatus {
  /// The current state of the task's lifecycle.
  TaskState get state;

  /// An optional, human-readable message providing more details about the
  /// current status.
  Message? get message;

  /// An ISO 8601 datetime string indicating when this status was recorded.
  String? get timestamp;

  /// Create a copy of TaskStatus
  /// with the given fields replaced by the non-null parameter values.
  @JsonKey(includeFromJson: false, includeToJson: false)
  @pragma('vm:prefer-inline')
  $TaskStatusCopyWith<TaskStatus> get copyWith =>
      _$TaskStatusCopyWithImpl<TaskStatus>(this as TaskStatus, _$identity);

  /// Serializes this TaskStatus to a JSON map.
  Map<String, dynamic> toJson();

  @override
  bool operator ==(Object other) {
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is TaskStatus &&
            (identical(other.state, state) || other.state == state) &&
            (identical(other.message, message) || other.message == message) &&
            (identical(other.timestamp, timestamp) ||
                other.timestamp == timestamp));
  }

  @JsonKey(includeFromJson: false, includeToJson: false)
  @override
  int get hashCode => Object.hash(runtimeType, state, message, timestamp);

  @override
  String toString() {
    return 'TaskStatus(state: $state, message: $message, timestamp: $timestamp)';
  }
}

/// @nodoc
abstract mixin class $TaskStatusCopyWith<$Res> {
  factory $TaskStatusCopyWith(
          TaskStatus value, $Res Function(TaskStatus) _then) =
      _$TaskStatusCopyWithImpl;
  @useResult
  $Res call({TaskState state, Message? message, String? timestamp});

  $MessageCopyWith<$Res>? get message;
}

/// @nodoc
class _$TaskStatusCopyWithImpl<$Res> implements $TaskStatusCopyWith<$Res> {
  _$TaskStatusCopyWithImpl(this._self, this._then);

  final TaskStatus _self;
  final $Res Function(TaskStatus) _then;

  /// Create a copy of TaskStatus
  /// with the given fields replaced by the non-null parameter values.
  @pragma('vm:prefer-inline')
  @override
  $Res call({
    Object? state = null,
    Object? message = freezed,
    Object? timestamp = freezed,
  }) {
    return _then(_self.copyWith(
      state: null == state
          ? _self.state
          : state // ignore: cast_nullable_to_non_nullable
              as TaskState,
      message: freezed == message
          ? _self.message
          : message // ignore: cast_nullable_to_non_nullable
              as Message?,
      timestamp: freezed == timestamp
          ? _self.timestamp
          : timestamp // ignore: cast_nullable_to_non_nullable
              as String?,
    ));
  }

  /// Create a copy of TaskStatus
  /// with the given fields replaced by the non-null parameter values.
  @override
  @pragma('vm:prefer-inline')
  $MessageCopyWith<$Res>? get message {
    if (_self.message == null) {
      return null;
    }

    return $MessageCopyWith<$Res>(_self.message!, (value) {
      return _then(_self.copyWith(message: value));
    });
  }
}

/// Adds pattern-matching-related methods to [TaskStatus].
extension TaskStatusPatterns on TaskStatus {
  /// A variant of `map` that fallback to returning `orElse`.
  ///
  /// It is equivalent to doing:
  /// ```dart
  /// switch (sealedClass) {
  ///   case final Subclass value:
  ///     return ...;
  ///   case _:
  ///     return orElse();
  /// }
  /// ```

  @optionalTypeArgs
  TResult maybeMap<TResult extends Object?>(
    TResult Function(_TaskStatus value)? $default, {
    required TResult orElse(),
  }) {
    final _that = this;
    switch (_that) {
      case _TaskStatus() when $default != null:
        return $default(_that);
      case _:
        return orElse();
    }
  }

  /// A `switch`-like method, using callbacks.
  ///
  /// Callbacks receives the raw object, upcasted.
  /// It is equivalent to doing:
  /// ```dart
  /// switch (sealedClass) {
  ///   case final Subclass value:
  ///     return ...;
  ///   case final Subclass2 value:
  ///     return ...;
  /// }
  /// ```

  @optionalTypeArgs
  TResult map<TResult extends Object?>(
    TResult Function(_TaskStatus value) $default,
  ) {
    final _that = this;
    switch (_that) {
      case _TaskStatus():
        return $default(_that);
      case _:
        throw StateError('Unexpected subclass');
    }
  }

  /// A variant of `map` that fallback to returning `null`.
  ///
  /// It is equivalent to doing:
  /// ```dart
  /// switch (sealedClass) {
  ///   case final Subclass value:
  ///     return ...;
  ///   case _:
  ///     return null;
  /// }
  /// ```

  @optionalTypeArgs
  TResult? mapOrNull<TResult extends Object?>(
    TResult? Function(_TaskStatus value)? $default,
  ) {
    final _that = this;
    switch (_that) {
      case _TaskStatus() when $default != null:
        return $default(_that);
      case _:
        return null;
    }
  }

  /// A variant of `when` that fallback to an `orElse` callback.
  ///
  /// It is equivalent to doing:
  /// ```dart
  /// switch (sealedClass) {
  ///   case Subclass(:final field):
  ///     return ...;
  ///   case _:
  ///     return orElse();
  /// }
  /// ```

  @optionalTypeArgs
  TResult maybeWhen<TResult extends Object?>(
    TResult Function(TaskState state, Message? message, String? timestamp)?
        $default, {
    required TResult orElse(),
  }) {
    final _that = this;
    switch (_that) {
      case _TaskStatus() when $default != null:
        return $default(_that.state, _that.message, _that.timestamp);
      case _:
        return orElse();
    }
  }

  /// A `switch`-like method, using callbacks.
  ///
  /// As opposed to `map`, this offers destructuring.
  /// It is equivalent to doing:
  /// ```dart
  /// switch (sealedClass) {
  ///   case Subclass(:final field):
  ///     return ...;
  ///   case Subclass2(:final field2):
  ///     return ...;
  /// }
  /// ```

  @optionalTypeArgs
  TResult when<TResult extends Object?>(
    TResult Function(TaskState state, Message? message, String? timestamp)
        $default,
  ) {
    final _that = this;
    switch (_that) {
      case _TaskStatus():
        return $default(_that.state, _that.message, _that.timestamp);
      case _:
        throw StateError('Unexpected subclass');
    }
  }

  /// A variant of `when` that fallback to returning `null`
  ///
  /// It is equivalent to doing:
  /// ```dart
  /// switch (sealedClass) {
  ///   case Subclass(:final field):
  ///     return ...;
  ///   case _:
  ///     return null;
  /// }
  /// ```

  @optionalTypeArgs
  TResult? whenOrNull<TResult extends Object?>(
    TResult? Function(TaskState state, Message? message, String? timestamp)?
        $default,
  ) {
    final _that = this;
    switch (_that) {
      case _TaskStatus() when $default != null:
        return $default(_that.state, _that.message, _that.timestamp);
      case _:
        return null;
    }
  }
}

/// @nodoc
@JsonSerializable()
class _TaskStatus implements TaskStatus {
  const _TaskStatus({required this.state, this.message, this.timestamp});
  factory _TaskStatus.fromJson(Map<String, dynamic> json) =>
      _$TaskStatusFromJson(json);

  /// The current state of the task's lifecycle.
  @override
  final TaskState state;

  /// An optional, human-readable message providing more details about the
  /// current status.
  @override
  final Message? message;

  /// An ISO 8601 datetime string indicating when this status was recorded.
  @override
  final String? timestamp;

  /// Create a copy of TaskStatus
  /// with the given fields replaced by the non-null parameter values.
  @override
  @JsonKey(includeFromJson: false, includeToJson: false)
  @pragma('vm:prefer-inline')
  _$TaskStatusCopyWith<_TaskStatus> get copyWith =>
      __$TaskStatusCopyWithImpl<_TaskStatus>(this, _$identity);

  @override
  Map<String, dynamic> toJson() {
    return _$TaskStatusToJson(
      this,
    );
  }

  @override
  bool operator ==(Object other) {
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is _TaskStatus &&
            (identical(other.state, state) || other.state == state) &&
            (identical(other.message, message) || other.message == message) &&
            (identical(other.timestamp, timestamp) ||
                other.timestamp == timestamp));
  }

  @JsonKey(includeFromJson: false, includeToJson: false)
  @override
  int get hashCode => Object.hash(runtimeType, state, message, timestamp);

  @override
  String toString() {
    return 'TaskStatus(state: $state, message: $message, timestamp: $timestamp)';
  }
}

/// @nodoc
abstract mixin class _$TaskStatusCopyWith<$Res>
    implements $TaskStatusCopyWith<$Res> {
  factory _$TaskStatusCopyWith(
          _TaskStatus value, $Res Function(_TaskStatus) _then) =
      __$TaskStatusCopyWithImpl;
  @override
  @useResult
  $Res call({TaskState state, Message? message, String? timestamp});

  @override
  $MessageCopyWith<$Res>? get message;
}

/// @nodoc
class __$TaskStatusCopyWithImpl<$Res> implements _$TaskStatusCopyWith<$Res> {
  __$TaskStatusCopyWithImpl(this._self, this._then);

  final _TaskStatus _self;
  final $Res Function(_TaskStatus) _then;

  /// Create a copy of TaskStatus
  /// with the given fields replaced by the non-null parameter values.
  @override
  @pragma('vm:prefer-inline')
  $Res call({
    Object? state = null,
    Object? message = freezed,
    Object? timestamp = freezed,
  }) {
    return _then(_TaskStatus(
      state: null == state
          ? _self.state
          : state // ignore: cast_nullable_to_non_nullable
              as TaskState,
      message: freezed == message
          ? _self.message
          : message // ignore: cast_nullable_to_non_nullable
              as Message?,
      timestamp: freezed == timestamp
          ? _self.timestamp
          : timestamp // ignore: cast_nullable_to_non_nullable
              as String?,
    ));
  }

  /// Create a copy of TaskStatus
  /// with the given fields replaced by the non-null parameter values.
  @override
  @pragma('vm:prefer-inline')
  $MessageCopyWith<$Res>? get message {
    if (_self.message == null) {
      return null;
    }

    return $MessageCopyWith<$Res>(_self.message!, (value) {
      return _then(_self.copyWith(message: value));
    });
  }
}

/// @nodoc
mixin _$Artifact {
  /// A unique identifier (e.g. UUID) for the artifact within the scope of the
  /// task.
  String get artifactId;

  /// An optional, human-readable name for the artifact.
  String? get name;

  /// An optional, human-readable description of the artifact.
  String? get description;

  /// An array of content parts that make up the artifact.
  List<Part> get parts;

  /// Optional metadata for extensions. The key is an extension-specific
  /// identifier.
  Map<String, dynamic>? get metadata;

  /// The URIs of extensions that are relevant to this artifact.
  List<String>? get extensions;

  /// Create a copy of Artifact
  /// with the given fields replaced by the non-null parameter values.
  @JsonKey(includeFromJson: false, includeToJson: false)
  @pragma('vm:prefer-inline')
  $ArtifactCopyWith<Artifact> get copyWith =>
      _$ArtifactCopyWithImpl<Artifact>(this as Artifact, _$identity);

  /// Serializes this Artifact to a JSON map.
  Map<String, dynamic> toJson();

  @override
  bool operator ==(Object other) {
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is Artifact &&
            (identical(other.artifactId, artifactId) ||
                other.artifactId == artifactId) &&
            (identical(other.name, name) || other.name == name) &&
            (identical(other.description, description) ||
                other.description == description) &&
            const DeepCollectionEquality().equals(other.parts, parts) &&
            const DeepCollectionEquality().equals(other.metadata, metadata) &&
            const DeepCollectionEquality()
                .equals(other.extensions, extensions));
  }

  @JsonKey(includeFromJson: false, includeToJson: false)
  @override
  int get hashCode => Object.hash(
      runtimeType,
      artifactId,
      name,
      description,
      const DeepCollectionEquality().hash(parts),
      const DeepCollectionEquality().hash(metadata),
      const DeepCollectionEquality().hash(extensions));

  @override
  String toString() {
    return 'Artifact(artifactId: $artifactId, name: $name, description: $description, parts: $parts, metadata: $metadata, extensions: $extensions)';
  }
}

/// @nodoc
abstract mixin class $ArtifactCopyWith<$Res> {
  factory $ArtifactCopyWith(Artifact value, $Res Function(Artifact) _then) =
      _$ArtifactCopyWithImpl;
  @useResult
  $Res call(
      {String artifactId,
      String? name,
      String? description,
      List<Part> parts,
      Map<String, dynamic>? metadata,
      List<String>? extensions});
}

/// @nodoc
class _$ArtifactCopyWithImpl<$Res> implements $ArtifactCopyWith<$Res> {
  _$ArtifactCopyWithImpl(this._self, this._then);

  final Artifact _self;
  final $Res Function(Artifact) _then;

  /// Create a copy of Artifact
  /// with the given fields replaced by the non-null parameter values.
  @pragma('vm:prefer-inline')
  @override
  $Res call({
    Object? artifactId = null,
    Object? name = freezed,
    Object? description = freezed,
    Object? parts = null,
    Object? metadata = freezed,
    Object? extensions = freezed,
  }) {
    return _then(_self.copyWith(
      artifactId: null == artifactId
          ? _self.artifactId
          : artifactId // ignore: cast_nullable_to_non_nullable
              as String,
      name: freezed == name
          ? _self.name
          : name // ignore: cast_nullable_to_non_nullable
              as String?,
      description: freezed == description
          ? _self.description
          : description // ignore: cast_nullable_to_non_nullable
              as String?,
      parts: null == parts
          ? _self.parts
          : parts // ignore: cast_nullable_to_non_nullable
              as List<Part>,
      metadata: freezed == metadata
          ? _self.metadata
          : metadata // ignore: cast_nullable_to_non_nullable
              as Map<String, dynamic>?,
      extensions: freezed == extensions
          ? _self.extensions
          : extensions // ignore: cast_nullable_to_non_nullable
              as List<String>?,
    ));
  }
}

/// Adds pattern-matching-related methods to [Artifact].
extension ArtifactPatterns on Artifact {
  /// A variant of `map` that fallback to returning `orElse`.
  ///
  /// It is equivalent to doing:
  /// ```dart
  /// switch (sealedClass) {
  ///   case final Subclass value:
  ///     return ...;
  ///   case _:
  ///     return orElse();
  /// }
  /// ```

  @optionalTypeArgs
  TResult maybeMap<TResult extends Object?>(
    TResult Function(_Artifact value)? $default, {
    required TResult orElse(),
  }) {
    final _that = this;
    switch (_that) {
      case _Artifact() when $default != null:
        return $default(_that);
      case _:
        return orElse();
    }
  }

  /// A `switch`-like method, using callbacks.
  ///
  /// Callbacks receives the raw object, upcasted.
  /// It is equivalent to doing:
  /// ```dart
  /// switch (sealedClass) {
  ///   case final Subclass value:
  ///     return ...;
  ///   case final Subclass2 value:
  ///     return ...;
  /// }
  /// ```

  @optionalTypeArgs
  TResult map<TResult extends Object?>(
    TResult Function(_Artifact value) $default,
  ) {
    final _that = this;
    switch (_that) {
      case _Artifact():
        return $default(_that);
      case _:
        throw StateError('Unexpected subclass');
    }
  }

  /// A variant of `map` that fallback to returning `null`.
  ///
  /// It is equivalent to doing:
  /// ```dart
  /// switch (sealedClass) {
  ///   case final Subclass value:
  ///     return ...;
  ///   case _:
  ///     return null;
  /// }
  /// ```

  @optionalTypeArgs
  TResult? mapOrNull<TResult extends Object?>(
    TResult? Function(_Artifact value)? $default,
  ) {
    final _that = this;
    switch (_that) {
      case _Artifact() when $default != null:
        return $default(_that);
      case _:
        return null;
    }
  }

  /// A variant of `when` that fallback to an `orElse` callback.
  ///
  /// It is equivalent to doing:
  /// ```dart
  /// switch (sealedClass) {
  ///   case Subclass(:final field):
  ///     return ...;
  ///   case _:
  ///     return orElse();
  /// }
  /// ```

  @optionalTypeArgs
  TResult maybeWhen<TResult extends Object?>(
    TResult Function(
            String artifactId,
            String? name,
            String? description,
            List<Part> parts,
            Map<String, dynamic>? metadata,
            List<String>? extensions)?
        $default, {
    required TResult orElse(),
  }) {
    final _that = this;
    switch (_that) {
      case _Artifact() when $default != null:
        return $default(_that.artifactId, _that.name, _that.description,
            _that.parts, _that.metadata, _that.extensions);
      case _:
        return orElse();
    }
  }

  /// A `switch`-like method, using callbacks.
  ///
  /// As opposed to `map`, this offers destructuring.
  /// It is equivalent to doing:
  /// ```dart
  /// switch (sealedClass) {
  ///   case Subclass(:final field):
  ///     return ...;
  ///   case Subclass2(:final field2):
  ///     return ...;
  /// }
  /// ```

  @optionalTypeArgs
  TResult when<TResult extends Object?>(
    TResult Function(
            String artifactId,
            String? name,
            String? description,
            List<Part> parts,
            Map<String, dynamic>? metadata,
            List<String>? extensions)
        $default,
  ) {
    final _that = this;
    switch (_that) {
      case _Artifact():
        return $default(_that.artifactId, _that.name, _that.description,
            _that.parts, _that.metadata, _that.extensions);
      case _:
        throw StateError('Unexpected subclass');
    }
  }

  /// A variant of `when` that fallback to returning `null`
  ///
  /// It is equivalent to doing:
  /// ```dart
  /// switch (sealedClass) {
  ///   case Subclass(:final field):
  ///     return ...;
  ///   case _:
  ///     return null;
  /// }
  /// ```

  @optionalTypeArgs
  TResult? whenOrNull<TResult extends Object?>(
    TResult? Function(
            String artifactId,
            String? name,
            String? description,
            List<Part> parts,
            Map<String, dynamic>? metadata,
            List<String>? extensions)?
        $default,
  ) {
    final _that = this;
    switch (_that) {
      case _Artifact() when $default != null:
        return $default(_that.artifactId, _that.name, _that.description,
            _that.parts, _that.metadata, _that.extensions);
      case _:
        return null;
    }
  }
}

/// @nodoc
@JsonSerializable()
class _Artifact implements Artifact {
  const _Artifact(
      {required this.artifactId,
      this.name,
      this.description,
      required final List<Part> parts,
      final Map<String, dynamic>? metadata,
      final List<String>? extensions})
      : _parts = parts,
        _metadata = metadata,
        _extensions = extensions;
  factory _Artifact.fromJson(Map<String, dynamic> json) =>
      _$ArtifactFromJson(json);

  /// A unique identifier (e.g. UUID) for the artifact within the scope of the
  /// task.
  @override
  final String artifactId;

  /// An optional, human-readable name for the artifact.
  @override
  final String? name;

  /// An optional, human-readable description of the artifact.
  @override
  final String? description;

  /// An array of content parts that make up the artifact.
  final List<Part> _parts;

  /// An array of content parts that make up the artifact.
  @override
  List<Part> get parts {
    if (_parts is EqualUnmodifiableListView) return _parts;
    // ignore: implicit_dynamic_type
    return EqualUnmodifiableListView(_parts);
  }

  /// Optional metadata for extensions. The key is an extension-specific
  /// identifier.
  final Map<String, dynamic>? _metadata;

  /// Optional metadata for extensions. The key is an extension-specific
  /// identifier.
  @override
  Map<String, dynamic>? get metadata {
    final value = _metadata;
    if (value == null) return null;
    if (_metadata is EqualUnmodifiableMapView) return _metadata;
    // ignore: implicit_dynamic_type
    return EqualUnmodifiableMapView(value);
  }

  /// The URIs of extensions that are relevant to this artifact.
  final List<String>? _extensions;

  /// The URIs of extensions that are relevant to this artifact.
  @override
  List<String>? get extensions {
    final value = _extensions;
    if (value == null) return null;
    if (_extensions is EqualUnmodifiableListView) return _extensions;
    // ignore: implicit_dynamic_type
    return EqualUnmodifiableListView(value);
  }

  /// Create a copy of Artifact
  /// with the given fields replaced by the non-null parameter values.
  @override
  @JsonKey(includeFromJson: false, includeToJson: false)
  @pragma('vm:prefer-inline')
  _$ArtifactCopyWith<_Artifact> get copyWith =>
      __$ArtifactCopyWithImpl<_Artifact>(this, _$identity);

  @override
  Map<String, dynamic> toJson() {
    return _$ArtifactToJson(
      this,
    );
  }

  @override
  bool operator ==(Object other) {
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is _Artifact &&
            (identical(other.artifactId, artifactId) ||
                other.artifactId == artifactId) &&
            (identical(other.name, name) || other.name == name) &&
            (identical(other.description, description) ||
                other.description == description) &&
            const DeepCollectionEquality().equals(other._parts, _parts) &&
            const DeepCollectionEquality().equals(other._metadata, _metadata) &&
            const DeepCollectionEquality()
                .equals(other._extensions, _extensions));
  }

  @JsonKey(includeFromJson: false, includeToJson: false)
  @override
  int get hashCode => Object.hash(
      runtimeType,
      artifactId,
      name,
      description,
      const DeepCollectionEquality().hash(_parts),
      const DeepCollectionEquality().hash(_metadata),
      const DeepCollectionEquality().hash(_extensions));

  @override
  String toString() {
    return 'Artifact(artifactId: $artifactId, name: $name, description: $description, parts: $parts, metadata: $metadata, extensions: $extensions)';
  }
}

/// @nodoc
abstract mixin class _$ArtifactCopyWith<$Res>
    implements $ArtifactCopyWith<$Res> {
  factory _$ArtifactCopyWith(_Artifact value, $Res Function(_Artifact) _then) =
      __$ArtifactCopyWithImpl;
  @override
  @useResult
  $Res call(
      {String artifactId,
      String? name,
      String? description,
      List<Part> parts,
      Map<String, dynamic>? metadata,
      List<String>? extensions});
}

/// @nodoc
class __$ArtifactCopyWithImpl<$Res> implements _$ArtifactCopyWith<$Res> {
  __$ArtifactCopyWithImpl(this._self, this._then);

  final _Artifact _self;
  final $Res Function(_Artifact) _then;

  /// Create a copy of Artifact
  /// with the given fields replaced by the non-null parameter values.
  @override
  @pragma('vm:prefer-inline')
  $Res call({
    Object? artifactId = null,
    Object? name = freezed,
    Object? description = freezed,
    Object? parts = null,
    Object? metadata = freezed,
    Object? extensions = freezed,
  }) {
    return _then(_Artifact(
      artifactId: null == artifactId
          ? _self.artifactId
          : artifactId // ignore: cast_nullable_to_non_nullable
              as String,
      name: freezed == name
          ? _self.name
          : name // ignore: cast_nullable_to_non_nullable
              as String?,
      description: freezed == description
          ? _self.description
          : description // ignore: cast_nullable_to_non_nullable
              as String?,
      parts: null == parts
          ? _self._parts
          : parts // ignore: cast_nullable_to_non_nullable
              as List<Part>,
      metadata: freezed == metadata
          ? _self._metadata
          : metadata // ignore: cast_nullable_to_non_nullable
              as Map<String, dynamic>?,
      extensions: freezed == extensions
          ? _self._extensions
          : extensions // ignore: cast_nullable_to_non_nullable
              as List<String>?,
    ));
  }
}

// dart format on
