name: hotel_tool
description: A tool to checkout a hotel.
version: 0.0.1

environment:
  sdk: ^3.10.0-75.1.beta

# Add regular dependencies here.
dependencies:
  path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
