name: dart_schema_builder
description: A sample command-line application.
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  args: ^2.7.0
  characters: ^1.4.1
  collection: ^1.19.1
  decimal: ^3.2.4
  http: ^1.4.0
  intl: ^0.20.2
  mockito: ^5.5.0
  path: ^1.9.0

dev_dependencies:
  dart_flutter_team_lints: ^3.5.2
  lints: ^6.0.0
  test: ^1.25.6
