name: example
publish_to: 'none'

environment:
  sdk: ^3.9.0-196.0.dev

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  dart_flutter_team_lints: ^3.5.2

flutter:
  uses-material-design: true
  assets:
    - assets/explore/
    - assets/agent_icon.png
