name: minimal_genui
publish_to: "none" # Remove this line when we're ready to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  firebase_core: ^4.0.0
  flutter:
    sdk: flutter
  flutter_genui:
    path: ../../pkgs/flutter_genui

dev_dependencies:
  dart_flutter_team_lints: ^3.5.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
