name: chat_box_tester
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0-28.0.dev

dependencies:
  flutter:
    sdk: flutter
  flutter_genui:
    path: ../../flutter_genui

dev_dependencies:
  dart_flutter_team_lints: ^3.5.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
