# Copyright 2025 The Flutter Authors.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

name: flutter_genui_google_generative_ai
description: Integration package for flutter_genui and Google Cloud Generative Language API.
version: 0.1.0
homepage: https://github.com/flutter/genui/packages/flutter_genui_google_generative_ai
license: BSD-3-Clause
issue_tracker: https://github.com/flutter/genui/issues
publish_to: none

environment:
  sdk: ">=3.9.2 <4.0.0"
  flutter: ">=3.35.7"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_genui:
    path: ../flutter_genui
  google_cloud_ai_generativelanguage_v1beta: ^0.1.0
  google_cloud_protobuf: ^0.1.0
  json_schema_builder: ^0.1.3

dev_dependencies:
  dart_flutter_team_lints: ^3.5.2
  flutter_test:
    sdk: flutter
  logging: ^1.3.0

