// Copyright 2025 The Flutter Authors.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Mocks generated by Mockito 5.4.6 from annotations
// in a2a_dart/test/server/create_task_handler_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:a2a_dart/src/core/task.dart' as _i2;
import 'package:a2a_dart/src/server/task_manager.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeTask_0 extends _i1.SmartFake implements _i2.Task {
  _FakeTask_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TaskManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskManager extends _i1.Mock implements _i3.TaskManager {
  MockTaskManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Task createTask() => (super.noSuchMethod(
        Invocation.method(
          #createTask,
          [],
        ),
        returnValue: _FakeTask_0(
          this,
          Invocation.method(
            #createTask,
            [],
          ),
        ),
      ) as _i2.Task);

  @override
  _i2.Task? getTask(String? taskId) => (super.noSuchMethod(Invocation.method(
        #getTask,
        [taskId],
      )) as _i2.Task?);

  @override
  void updateTask(_i2.Task? task) => super.noSuchMethod(
        Invocation.method(
          #updateTask,
          [task],
        ),
        returnValueForMissingStub: null,
      );
}
