name: fcp_client_example
description: An example app for the fcp_client package.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  fcp_client:
    path: ../
  cupertino_icons: ^1.0.8
  flutter_driver:
    sdk: flutter

dev_dependencies:
  test: ^1.26.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
