name: example
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.0-101.0.dev

dependencies:
  flutter:
    sdk: flutter
  ai_client:
    path: ../../ai_client
  dart_schema_builder:
    path: ../../../dart_schema_builder
  fcp_client:
    path: ../../fcp_client
  fcp_tools:
    path: ..
  firebase_ai: ^3.0.0
  firebase_app_check: ^0.4.0
  firebase_auth: ^6.0.0
  firebase_core: ^4.0.0
  firebase_core_platform_interface: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
