// Copyright 2025 The Flutter Authors.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import 'dart:async';
import 'dart:convert';
import 'dart:typed_data';

import 'package:dartantic_ai/dartantic_ai.dart' as dartantic;
import 'package:googleai_dart/googleai_dart.dart' as googleai;
import 'package:http/http.dart' as http;

import '../primitives/climbing/climbing_db.dart';
import 'api_key/api_key.dart';

/// An abstract interface for AI clients.
abstract interface class AiClient {
  /// Sends a message stream request to the AI service.
  ///
  /// [prompt] is the user's message.
  /// [history] is the conversation history.
  Stream<String> sendStream(
    String prompt, {
    required List<dartantic.ChatMessage> history,
  });

  /// Dispose of resources.
  void dispose();
}

/// A video generated by the Veo API.
class GeneratedVideo {
  /// Creates a [GeneratedVideo].
  const GeneratedVideo({this.bytes, this.uri, this.mimeType});

  /// The raw bytes of the generated video, if available.
  final Uint8List? bytes;

  /// The remote URI of the generated video, if the API returned a link instead
  /// of inline data.
  final Uri? uri;

  /// The MIME type of the generated video (e.g. `video/mp4`).
  final String? mimeType;

  /// Whether no video content was produced.
  bool get isEmpty => (bytes == null || bytes!.isEmpty) && uri == null;
}

/// An implementation of [AiClient] using `package:dartantic_ai`.
class GeminiDartanticAiClient implements AiClient {
  GeminiDartanticAiClient({String? modelName, String? videoModelName})
    : _apiKey = apiKey(),
      _videoModelName = videoModelName ?? defaultVeoModel {
    _provider = dartantic.GoogleProvider(apiKey: _apiKey);
    _agent = dartantic.Agent.forProvider(
      _provider,
      chatModelName: modelName ?? 'gemini-3-flash-preview',
      tools: [
        dartantic.Tool(
          name: 'listClimbingLocations',
          description: 'Lists all available climbing locations.',
          onCall: (args) => climbingLocations.map((e) => e.toJson()).toList(),
        ),
      ],
    );
    _mediaClient = googleai.GoogleAIClient.withApiKey(_apiKey);
  }

  /// The default Veo model used for video generation.
  static const String defaultVeoModel = 'veo-3.0-fast-generate-001';

  final String _apiKey;
  final String _videoModelName;

  late final dartantic.GoogleProvider _provider;
  late final dartantic.Agent _agent;
  late final googleai.GoogleAIClient _mediaClient;

  @override
  Stream<String> sendStream(
    String prompt, {
    required List<dartantic.ChatMessage> history,
  }) async* {
    final Stream<dartantic.ChatResult<String>> stream = _agent.sendStream(
      prompt,
      history: history,
    );

    await for (final result in stream) {
      if (result.output.isNotEmpty) {
        yield result.output;
      }
    }
  }

  /// Generates a video from a text [prompt] using the Gemini Veo API.
  ///
  /// Veo generation is asynchronous: the request kicks off a long-running
  /// operation that is polled (every [pollInterval]) until it completes or
  /// [timeout] elapses. When a sample is produced, its bytes are returned
  /// inline when present, otherwise downloaded from the returned URI.
  ///
  /// [negativePrompt] describes content to avoid, and [aspectRatio] (for
  /// example `16:9` or `9:16`) controls the framing.
  Future<GeneratedVideo> generateVideo(
    String prompt, {
    String? negativePrompt,
    String? aspectRatio,
    Duration pollInterval = const Duration(seconds: 10),
    Duration timeout = const Duration(minutes: 6),
  }) async {
    final parameters = <String, dynamic>{
      'aspectRatio': ?aspectRatio,
      'negativePrompt': ?negativePrompt,
    };

    final googleai.PredictLongRunningOperation operation = await _mediaClient
        .models
        .predictLongRunning(
          model: _videoModelName,
          instances: [
            {'prompt': prompt},
          ],
          parameters: parameters.isEmpty ? null : parameters,
        );

    final String? operationName = operation.name;
    if (operationName == null) {
      throw StateError('Veo did not return a long-running operation name.');
    }

    // Poll the operation until it completes (or we time out). The initial
    // request may already be done in rare cases.
    Map<String, dynamic>? responseJson = operation.response?.toJson();
    bool done = operation.done;
    final stopwatch = Stopwatch()..start();
    while (!done) {
      if (stopwatch.elapsed > timeout) {
        throw TimeoutException('Veo video generation timed out.', timeout);
      }
      await Future<void>.delayed(pollInterval);

      final googleai.Operation polled = await _mediaClient.models
          .operations(model: _videoModelName)
          .get(name: operationName);

      done = polled.done;
      if (done) {
        if (polled.error != null) {
          throw StateError(
            'Veo video generation failed: ${polled.error!.message}',
          );
        }
        responseJson = polled.response;
      }
    }

    if (responseJson == null) {
      throw StateError('Veo operation completed without a response.');
    }

    final googleai.PredictLongRunningGeneratedVideoResponse? videoResponse =
        googleai.PredictLongRunningResponse.fromJson(
          responseJson,
        ).generateVideoResponse;
    final List<googleai.Media>? samples = videoResponse?.generatedSamples;
    if (samples == null || samples.isEmpty) {
      final List<String>? reasons = videoResponse?.raiMediaFilteredReasons;
      throw StateError(
        'Veo returned no video samples'
        '${reasons == null ? '.' : ' (filtered: ${reasons.join(', ')}).'}',
      );
    }

    final googleai.Video? video = samples.first.video;
    const mimeType = 'video/mp4';

    // Veo may return the video inline (base64) or as a downloadable URI.
    final String? inline = video?.video;
    if (inline != null && inline.isNotEmpty) {
      return GeneratedVideo(bytes: base64Decode(inline), mimeType: mimeType);
    }

    final String? uriString = video?.uri;
    if (uriString != null && uriString.isNotEmpty) {
      final Uri uri = Uri.parse(uriString);
      return GeneratedVideo(
        bytes: await _downloadVideo(uri),
        uri: uri,
        mimeType: mimeType,
      );
    }

    return const GeneratedVideo(mimeType: mimeType);
  }

  Future<Uint8List> _downloadVideo(Uri uri) async {
    final http.Response response = await http.get(
      uri,
      headers: {'x-goog-api-key': _apiKey},
    );
    if (response.statusCode != 200) {
      throw StateError(
        'Failed to download generated video from $uri '
        '(HTTP ${response.statusCode}).',
      );
    }
    return response.bodyBytes;
  }

  @override
  void dispose() {
    _mediaClient.close();
  }
}
