// Copyright 2025 The Flutter Authors.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import 'package:a2ui_core/a2ui_core.dart' as core;
import 'package:collection/collection.dart';
import 'package:flutter/material.dart';

import '../interfaces/surface_context.dart';
import '../model/catalog.dart';
import '../model/catalog_item.dart';
import '../model/data_model.dart';
import '../model/ui_models.dart';
import '../primitives/logging.dart';
import '../primitives/simple_items.dart';
import 'fallback_widget.dart';

/// A callback for when a user interacts with a widget.
typedef UiEventCallback = void Function(UiEvent event);

/// A widget that renders a dynamic UI surface generated by the AI.
///
/// Drives off [SurfaceContext.definition] by default; when the context also
/// implements [LiveSurfaceContext] (GenUI's own controller does), the renderer
/// subscribes to per-component updates from the live core surface model for
/// granular rebuilds.
class Surface extends StatefulWidget {
  /// Creates a [Surface].
  const Surface({
    super.key,
    required this.surfaceContext,
    this.defaultBuilder,
    this.actionDelegate = const DefaultActionDelegate(),
  });

  /// The context that holds the state of this surface.
  final SurfaceContext surfaceContext;

  /// A builder for the widget to display when the surface has no definition.
  final WidgetBuilder? defaultBuilder;

  /// The delegate that handles UI actions.
  final ActionDelegate actionDelegate;

  @override
  State<Surface> createState() => _SurfaceState();
}

class _SurfaceState extends State<Surface> {
  core.SurfaceModel? _trackedSurface;
  void Function(core.ComponentModel)? _onCreated;
  void Function(String)? _onDeleted;

  LiveSurfaceContext? get _liveContext =>
      widget.surfaceContext is LiveSurfaceContext
      ? widget.surfaceContext as LiveSurfaceContext
      : null;

  @override
  void initState() {
    super.initState();
    final LiveSurfaceContext? liveContext = _liveContext;
    if (liveContext != null) {
      liveContext.surface.addListener(_onSurfaceChanged);
      _attachComponentsListeners(liveContext.surface.value);
    } else {
      widget.surfaceContext.definition.addListener(_onDefinitionChanged);
    }
  }

  @override
  void didUpdateWidget(Surface oldWidget) {
    super.didUpdateWidget(oldWidget);
    if (oldWidget.surfaceContext == widget.surfaceContext) return;

    if (oldWidget.surfaceContext is LiveSurfaceContext) {
      (oldWidget.surfaceContext as LiveSurfaceContext).surface.removeListener(
        _onSurfaceChanged,
      );
      _detachComponentsListeners();
    } else {
      oldWidget.surfaceContext.definition.removeListener(_onDefinitionChanged);
    }

    final LiveSurfaceContext? liveContext = _liveContext;
    if (liveContext != null) {
      liveContext.surface.addListener(_onSurfaceChanged);
      _attachComponentsListeners(liveContext.surface.value);
    } else {
      widget.surfaceContext.definition.addListener(_onDefinitionChanged);
    }
  }

  @override
  void dispose() {
    final LiveSurfaceContext? liveContext = _liveContext;
    if (liveContext != null) {
      liveContext.surface.removeListener(_onSurfaceChanged);
      _detachComponentsListeners();
    } else {
      widget.surfaceContext.definition.removeListener(_onDefinitionChanged);
    }
    super.dispose();
  }

  void _onDefinitionChanged() {
    if (mounted) setState(() {});
  }

  void _onSurfaceChanged() {
    final core.SurfaceModel? next = _liveContext?.surface.value;
    if (!identical(next, _trackedSurface)) {
      _detachComponentsListeners();
      _attachComponentsListeners(next);
    }
    if (mounted) setState(() {});
  }

  void _attachComponentsListeners(core.SurfaceModel? surface) {
    _trackedSurface = surface;
    if (surface == null) return;
    _onCreated = (component) {
      if (mounted) setState(() {});
    };
    _onDeleted = (id) {
      if (mounted) setState(() {});
    };
    surface.componentsModel.onCreated.addListener(_onCreated!);
    surface.componentsModel.onDeleted.addListener(_onDeleted!);
  }

  void _detachComponentsListeners() {
    final core.SurfaceModel<core.ComponentApi>? surface = _trackedSurface;
    if (surface != null && _onCreated != null && _onDeleted != null) {
      surface.componentsModel.onCreated.removeListener(_onCreated!);
      surface.componentsModel.onDeleted.removeListener(_onDeleted!);
    }
    _onCreated = null;
    _onDeleted = null;
    _trackedSurface = null;
  }

  @override
  Widget build(BuildContext context) {
    final LiveSurfaceContext? liveContext = _liveContext;
    if (liveContext != null) {
      return _buildLiveSurface(liveContext);
    }
    return _buildDefinitionSurface(widget.surfaceContext.definition.value);
  }

  Widget _buildLiveSurface(LiveSurfaceContext surfaceContext) {
    final core.SurfaceModel? surface = surfaceContext.surface.value;
    genUiLogger.fine('Building surface ${widget.surfaceContext.surfaceId}');

    if (surface == null) {
      genUiLogger.info(
        'Surface ${widget.surfaceContext.surfaceId} has no model yet.',
      );
      return widget.defaultBuilder?.call(context) ?? const SizedBox.shrink();
    }

    const rootId = 'root';
    if (surface.componentsModel.get(rootId) == null) {
      genUiLogger.warning(
        'Surface ${widget.surfaceContext.surfaceId} has no root component.',
      );
      return const SizedBox.shrink();
    }

    final Catalog? catalog = widget.surfaceContext.catalog;
    if (catalog == null) {
      final error = Exception(
        'Catalog with id "${surface.catalog.id}" not found.',
      );
      genUiLogger.severe(error.toString());
      widget.surfaceContext.reportError(error, StackTrace.current);
      return FallbackWidget(error: error);
    }

    return _buildLiveWidget(
      surface,
      catalog,
      rootId,
      DataContext(
        widget.surfaceContext.dataModel,
        DataPath.root,
        functions: catalog.functions,
      ),
    );
  }

  Widget _buildDefinitionSurface(SurfaceDefinition? definition) {
    genUiLogger.fine('Building surface ${widget.surfaceContext.surfaceId}');
    if (definition == null) {
      genUiLogger.info(
        'Surface ${widget.surfaceContext.surfaceId} has no definition.',
      );
      return widget.defaultBuilder?.call(context) ?? const SizedBox.shrink();
    }

    const rootId = 'root';
    if (definition.components.isEmpty ||
        !definition.components.containsKey(rootId)) {
      genUiLogger.warning(
        'Surface ${widget.surfaceContext.surfaceId} has no root component.',
      );
      return const SizedBox.shrink();
    }

    final Catalog? catalog = _findCatalogForDefinition(definition);
    if (catalog == null) {
      final error = Exception(
        'Catalog with id "${definition.catalogId}" not found.',
      );
      widget.surfaceContext.reportError(error, StackTrace.current);
      return FallbackWidget(error: error);
    }

    return _buildWidgetFromDefinition(
      definition,
      catalog,
      rootId,
      DataContext(
        widget.surfaceContext.dataModel,
        DataPath.root,
        functions: catalog.functions,
      ),
    );
  }

  Widget _buildLiveWidget(
    core.SurfaceModel surface,
    Catalog catalog,
    String widgetId,
    DataContext dataContext,
  ) {
    final core.ComponentModel? data = surface.componentsModel.get(widgetId);
    if (data == null) {
      final error = Exception('Widget with id: $widgetId not found.');
      genUiLogger.severe(error.toString());
      widget.surfaceContext.reportError(error, StackTrace.current);
      return FallbackWidget(error: error);
    }

    return _ComponentBuilder(
      key: ValueKey<String>(widgetId),
      component: data,
      builder: (BuildContext ctx) {
        try {
          genUiLogger.finest('Building widget $widgetId');
          final coreCtx = core.ComponentContext(
            surface,
            data,
            basePath: dataContext.path.toString(),
          );
          return catalog.buildWidget(
            CatalogItemContext.fromCore(
              componentContext: coreCtx,
              buildChild: (String childId, [DataContext? childDataContext]) =>
                  _buildLiveWidget(
                    surface,
                    catalog,
                    childId,
                    childDataContext ?? dataContext,
                  ),
              dispatchEvent: _dispatchEvent,
              buildContext: ctx,
              dataContext: dataContext,
              getCatalogItem: (String type) =>
                  catalog.items.firstWhereOrNull((item) => item.name == type),
              reportError: widget.surfaceContext.reportError,
            ),
          );
        } catch (exception, stackTrace) {
          genUiLogger.severe(
            'Error building widget $widgetId',
            exception,
            stackTrace,
          );
          widget.surfaceContext.reportError(exception, stackTrace);
          return FallbackWidget(error: exception, stackTrace: stackTrace);
        }
      },
    );
  }

  Widget _buildWidgetFromDefinition(
    SurfaceDefinition definition,
    Catalog catalog,
    String widgetId,
    DataContext dataContext,
  ) {
    try {
      Component? data = definition.components[widgetId];
      if (data == null) {
        final error = Exception('Widget with id: $widgetId not found.');
        genUiLogger.severe(error.toString());
        widget.surfaceContext.reportError(error, StackTrace.current);
        return FallbackWidget(error: error);
      }

      final JsonMap widgetData = data.properties;
      genUiLogger.finest('Building widget $widgetId');
      return catalog.buildWidget(
        CatalogItemContext(
          id: widgetId,
          data: widgetData,
          type: data.type,
          buildChild: (String childId, [DataContext? childDataContext]) =>
              _buildWidgetFromDefinition(
                definition,
                catalog,
                childId,
                childDataContext ?? dataContext,
              ),
          dispatchEvent: _dispatchEvent,
          buildContext: context,
          dataContext: dataContext,
          getComponent: (String componentId) =>
              definition.components[componentId],
          getCatalogItem: (String type) =>
              catalog.items.firstWhereOrNull((item) => item.name == type),
          surfaceId: widget.surfaceContext.surfaceId,
          reportError: widget.surfaceContext.reportError,
        ),
      );
    } catch (exception, stackTrace) {
      genUiLogger.severe(
        'Error building widget $widgetId',
        exception,
        stackTrace,
      );
      widget.surfaceContext.reportError(exception, stackTrace);
      return FallbackWidget(error: exception, stackTrace: stackTrace);
    }
  }

  void _dispatchEvent(UiEvent event) {
    if (widget.actionDelegate.handleEvent(
      context,
      event,
      widget.surfaceContext,
      _buildWidgetFromDefinition,
    )) {
      return;
    }

    final Map<String, Object?> eventMap = {
      ...event.toMap(),
      surfaceIdKey: widget.surfaceContext.surfaceId,
    };
    final UiEvent newEvent = event is UserActionEvent
        ? UserActionEvent.fromMap(eventMap)
        : UiEvent.fromMap(eventMap);
    widget.surfaceContext.handleUiEvent(newEvent);
  }

  Catalog? _findCatalogForDefinition(SurfaceDefinition definition) {
    final Catalog? catalog = widget.surfaceContext.catalog;
    if (catalog == null) {
      genUiLogger.severe(
        'Catalog with id "${definition.catalogId}" not found for surface '
        '"${widget.surfaceContext.surfaceId}". Ensure the catalog is '
        'provided to SurfaceController.',
      );
    }
    return catalog;
  }
}

/// A delegate for handling UI actions in [Surface].
abstract interface class ActionDelegate {
  /// Handles a [UiEvent].
  ///
  /// Returns `true` if the event was handled, `false` otherwise.
  bool handleEvent(
    BuildContext context,
    UiEvent event,
    SurfaceContext genUiContext,
    Widget Function(SurfaceDefinition, Catalog, String, DataContext)
    buildWidget,
  );
}

/// The default action delegate that handles no actions itself.
class DefaultActionDelegate implements ActionDelegate {
  /// Creates a [DefaultActionDelegate].
  const DefaultActionDelegate();

  @override
  bool handleEvent(
    BuildContext context,
    UiEvent event,
    SurfaceContext genUiContext,
    Widget Function(SurfaceDefinition, Catalog, String, DataContext)
    buildWidget,
  ) {
    return false;
  }
}

/// Subscribes to a single [core.ComponentModel.onUpdated] and rebuilds its
/// child subtree when that component's properties change.
class _ComponentBuilder extends StatefulWidget {
  const _ComponentBuilder({
    super.key,
    required this.component,
    required this.builder,
  });

  final core.ComponentModel component;
  final WidgetBuilder builder;

  @override
  State<_ComponentBuilder> createState() => _ComponentBuilderState();
}

class _ComponentBuilderState extends State<_ComponentBuilder> {
  @override
  void initState() {
    super.initState();
    widget.component.onUpdated.addListener(_onComponentUpdated);
  }

  @override
  void didUpdateWidget(_ComponentBuilder oldWidget) {
    super.didUpdateWidget(oldWidget);
    if (!identical(oldWidget.component, widget.component)) {
      oldWidget.component.onUpdated.removeListener(_onComponentUpdated);
      widget.component.onUpdated.addListener(_onComponentUpdated);
    }
  }

  @override
  void dispose() {
    widget.component.onUpdated.removeListener(_onComponentUpdated);
    super.dispose();
  }

  void _onComponentUpdated(core.ComponentModel _) {
    if (mounted) setState(() {});
  }

  @override
  Widget build(BuildContext context) => widget.builder(context);
}
