name: fix_copyright
description: A command line app to fix copyright headers.
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  args: ^2.7.0
  dart_flutter_team_lints: ^3.5.2
  file: ^7.0.1
  path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
