# Copyright 2025 The Flutter Authors.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

name: example
description: A simple example for the a2ui_client package.
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  a2ui_client:
    path: ../
  flutter:
    sdk: flutter
  google_fonts: ^6.3.1
  gpt_markdown: ^1.1.4
  logging: ^1.3.0
  provider: ^6.1.5+1

dev_dependencies:
  dart_flutter_team_lints: ^3.5.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
