name: ui_primitives
description: Highly experimental package.
version: 0.0.1

resolution: workspace

environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  leak_tracker: any

dev_dependencies:
  test: ^1.26.2
