# Copyright 2025 The Flutter Authors.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

name: genui_express
description: Integrates A2UI Express compilation and local on-device AI engines with GenUI.
version: 0.1.0
publish_to: none
homepage: https://github.com/flutter/genui/tree/main/packages/genui_express
license: BSD-3-Clause
issue_tracker: https://github.com/flutter/genui/issues

environment:
  sdk: ^3.12.0
  flutter: ">=3.3.0"

resolution: workspace

dependencies:
  collection: any
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  genkit: ^0.13.2
  genui: ^0.9.1
  genui_express_macos:
    path: ../genui_express_macos
  genui_express_platform_interface:
    path: ../genui_express_platform_interface
  genui_express_web:
    path: ../genui_express_web
  plugin_platform_interface: ^2.0.2
  web: ^1.0.0
dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.genui_express
        pluginClass: GenuiExpressPlugin
      ios:
        pluginClass: GenuiExpressPlugin
      macos:
        default_package: genui_express_macos
      web:
        default_package: genui_express_web
