name: travel_app
description: A Flutter travel app example using flutter_genui.
publish_to: 'none'

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  firebase_core: ^4.0.0
  flutter:
    sdk: flutter
  flutter_genui:
    path: ../../flutter_genui
  url_launcher: ^6.2.6

dev_dependencies:
  dart_flutter_team_lints: ^3.5.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/explore/
    - assets/agent_icon.png
    - assets/result.png
