name: fcp_client
description: "A new Flutter package project."
version: 0.1.0
homepage:
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  file: ^7.0.1
  flutter:
    sdk: flutter
  json_patch: ^3.0.0
  json_schema: ^5.2.1
  platform: ^3.1.6

dev_dependencies:
  dart_flutter_team_lints: ^3.5.2
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  lints: ^6.0.0
  test: ^1.25.6

flutter:
