// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAuGlchtm3iQTUIbQGzckFXlBf7LO3ATk',
    appId: '1:192479449113:web:235a4ca94b58fce0711a88',
    messagingSenderId: '192479449113',
    projectId: 'flutter-genui',
    authDomain: 'flutter-genui.firebaseapp.com',
    storageBucket: 'flutter-genui.firebasestorage.app',
    measurementId: 'G-59ZQDQYLFB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvHPjnkjZwYhDDAS5b9D8r8rkDdWDvBKU',
    appId: '1:192479449113:android:d7ced77a2a05eb72711a88',
    messagingSenderId: '192479449113',
    projectId: 'flutter-genui',
    storageBucket: 'flutter-genui.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjn3GVihLiJ1kpmJP8_jB1lMlnG-HbTWk',
    appId: '1:192479449113:ios:99ab28b5ff55a0bf711a88',
    messagingSenderId: '192479449113',
    projectId: 'flutter-genui',
    storageBucket: 'flutter-genui.firebasestorage.app',
    iosBundleId: 'dev.flutter.genui.genuiClient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjn3GVihLiJ1kpmJP8_jB1lMlnG-HbTWk',
    appId: '1:192479449113:ios:99ab28b5ff55a0bf711a88',
    messagingSenderId: '192479449113',
    projectId: 'flutter-genui',
    storageBucket: 'flutter-genui.firebasestorage.app',
    iosBundleId: 'dev.flutter.genui.genuiClient',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAuGlchtm3iQTUIbQGzckFXlBf7LO3ATk',
    appId: '1:192479449113:web:c7bea58025b7eeed711a88',
    messagingSenderId: '192479449113',
    projectId: 'flutter-genui',
    authDomain: 'flutter-genui.firebaseapp.com',
    storageBucket: 'flutter-genui.firebasestorage.app',
    measurementId: 'G-05LK8KFYWS',
  );
}
