name: flutter_genui
description: "Flutter GenUI"
version: 0.0.1
homepage:

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.19.1
  file: ^7.0.1
  firebase_ai: ^3.0.0
  firebase_app_check: ^0.4.0
  firebase_auth: ^6.0.0
  firebase_core: ^4.0.0
  flutter:
    sdk: flutter
  json_rpc_2: ^4.0.0
  meta: ^1.16.0
  platform: ^3.1.6
  stream_channel: ^2.1.4
  url_launcher: ^6.2.6

dev_dependencies:
  dart_flutter_team_lints: ^3.5.2
  flutter_test:
    sdk: flutter
  network_image_mock: ^2.1.1
