name: flutter_genui
description: "Flutter GenUI"
version: 0.0.1
homepage:

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.19.1
  file: ^7.0.1
  firebase_ai: ^2.2.1
  firebase_app_check: ^0.3.0+1
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0
  flutter:
    sdk: flutter
  json_rpc_2: ^4.0.0
  platform: ^3.1.6
  stream_channel: ^2.1.4

dev_dependencies:
  dart_flutter_team_lints: ^3.5.2
  flutter_test:
    sdk: flutter
